# Generated by Django 5.0.4 on 2024-04-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToListenSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('listened', models.BooleanField(default=False)),
            ],
        ),
    ]
